---
- name: Clean Up
  hosts: all
  gather_facts: false
  tasks:
    - name: Load Scenario Variables
      ansible.builtin.include_vars: vars/main.yml
    - name: Clean Up
      ansible.builtin.file:
        path: "{{ download_save_location }}/{{ item.name }}"
        state: absent
      loop: "{{ download_remote_urls }}"
